workflows:
  ios-capacitor:
    name: iOS Capacitor Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      node: 22
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "app.lovable.c41f13761aba463197917f33c1ad45b0"
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Install Capacitor iOS
        script: |
          npm install @capacitor/ios
      - name: Build web assets
        script: |
          npm run build
      - name: Add iOS platform
        script: |
          npx cap add ios
          ls -la
          ls -la ios/App || echo "ios/App not found"
      - name: Update iOS platform
        script: |
          npx cap update ios
      - name: Sync Capacitor
        script: |
          npx cap sync ios
      - name: Install CocoaPods
        script: |
          cd ios/App && pod install --repo-update
      - name: Build iOS app
        script: |
          cd ios/App
          xcodebuild -workspace "App.xcworkspace" \
            -scheme "App" \
            -configuration Release \
            -sdk iphoneos \
            CODE_SIGNING_ALLOWED=NO
    artifacts:
      - ios/App/build/**/*.app
