workflows:
  ios-capacitor:
    name: iOS Capacitor Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Codemagic
    environment:
      node: 18
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "app.lovable.c41f13761aba463197917f33c1ad45b0"
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Build web assets
        script: |
          npm run build
      - name: Add iOS platform
        script: |
          npx cap add ios || true
      - name: Sync Capacitor
        script: |
          npx cap sync ios
      - name: Install CocoaPods
        script: |
          cd ios/App && pod install
      - name: Set up code signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          keychain add-certificates
          xcode-project use-profiles
      - name: Build iOS app
        script: |
          cd ios/App
          xcode-project build-ipa \
            --workspace "App.xcworkspace" \
            --scheme "App"
    artifacts:
      - ios/App/build/ios/ipa/*.ipa
      - ios/App/build/ios/xcarchive/*.xcarchive
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
