workflows:
  ios-capacitor:
    name: iOS Capacitor Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      node: 22
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "app.lovable.c41f13761aba463197917f33c1ad45b0"
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Build web assets
        script: |
          npm run build
      - name: Setup Capacitor iOS
        script: |
          # Install iOS platform package
          npm install @capacitor/ios --save
          # Initialize iOS project (skip pod install, we'll do it manually)
          CAPACITOR_SKIP_POD_INSTALL=true npx cap add ios || echo "iOS platform may already exist"
          # Verify ios folder was created
          ls -la ios/App || { echo "ERROR: ios/App not created"; exit 1; }
          # Sync web assets to iOS (skip pod install here too)
          CAPACITOR_SKIP_POD_INSTALL=true npx cap sync ios
      - name: Install CocoaPods dependencies
        script: |
          cd ios/App
          pod install --repo-update
      - name: Build iOS app
        script: |
          cd ios/App
          xcodebuild -workspace "App.xcworkspace" \
            -scheme "App" \
            -configuration Release \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            CODE_SIGNING_ALLOWED=NO \
            clean build
    artifacts:
      - ios/App/build/**/*.app
      - ios/App/build/**/*.ipa
