import { useState, useCallback } from 'react';
import { Sparkles } from 'lucide-react';
import { SkinForm } from '@/components/skin/SkinForm';
import { ImageCapture } from '@/components/skin/ImageCapture';
import { AnalysisResults } from '@/components/skin/AnalysisResults';
import { BottomNav } from '@/components/skin/BottomNav';
import { toast } from 'sonner';

interface SkinFormData {
  skinType: string;
  concerns: string[];
  climate: string;
  pollution: string;
}

interface AnalysisData {
  score: number;
  problems: { title: string; description: string; icon: 'hydration' | 'inflammation' | 'barrier' }[];
  deepAnalysis: string;
  avoidIngredients: { name: string; reason: string }[];
  prescriptionIngredients: { name: string; reason: string }[];
  routine: { time: 'AM' | 'PM' | 'BOTH'; step: number; product: string; productLink?: string; reason: string }[];
}

export default function Index() {
  const [activeTab, setActiveTab] = useState<'scan' | 'history' | 'settings'>('scan');
  const [formData, setFormData] = useState<SkinFormData | null>(null);
  const [imageData, setImageData] = useState<string | null>(null);
  const [isScanning, setIsScanning] = useState(false);
  const [analysisResults, setAnalysisResults] = useState<AnalysisData | null>(null);
  const [showValidationWarning, setShowValidationWarning] = useState(false);

  const isFormValid = formData?.skinType && formData.concerns.length > 0 && formData.climate && formData.pollution;

  const handleFormSubmit = useCallback((data: SkinFormData) => {
    setFormData(data);
    setShowValidationWarning(false);
  }, []);

  const handleImageCapture = useCallback((data: string) => {
    setImageData(data);
  }, []);

  const handleStartAnalysis = async () => {
    if (!isFormValid) {
      setShowValidationWarning(true);
      toast.error('Please complete the skin profile form above');
      return;
    }

    if (!imageData) {
      toast.error('Please capture or upload a photo');
      return;
    }

    setIsScanning(true);
    setShowValidationWarning(false);

    try {
      // Use direct fetch with timeout for better error handling
      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), 60000); // 60s timeout
      
      const response = await fetch(`${import.meta.env.VITE_SUPABASE_URL}/functions/v1/analyze-skin`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY}`,
          'apikey': import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY,
        },
        body: JSON.stringify({
          image: imageData,
          skinType: formData?.skinType,
          concerns: formData?.concerns,
          climate: formData?.climate,
          pollution: formData?.pollution,
        }),
        signal: controller.signal,
      });
      
      clearTimeout(timeoutId);

      if (!response.ok) {
        if (response.status === 429) {
          toast.error('Rate limit exceeded. Please try again in a moment.');
          return;
        } else if (response.status === 402) {
          toast.error('AI credits exhausted. Please add credits to continue.');
          return;
        }
        const errorText = await response.text();
        throw new Error(`Server error: ${response.status} - ${errorText}`);
      }

      const data = await response.json();

      setAnalysisResults(data);
      toast.success('Analysis complete!');
    } catch (err) {
      console.error('Analysis error:', err);
      toast.error('Failed to analyze skin. Please try again.');
    } finally {
      setIsScanning(false);
    }
  };

  const handleDownloadReport = () => {
    if (!analysisResults) return;
    
    const report = `
DERMATOLOGICAL INTELLIGENCE REPORT
===================================

SKIN HEALTH SCORE: ${analysisResults.score}/10

CORE PROBLEMS IDENTIFIED:
${analysisResults.problems.map(p => `• ${p.title}: ${p.description}`).join('\n')}

DEEP ANALYSIS:
${analysisResults.deepAnalysis}

INGREDIENTS TO AVOID:
${analysisResults.avoidIngredients.map(i => `• ${i.name}: ${i.reason}`).join('\n')}

PRESCRIPTION INGREDIENTS:
${analysisResults.prescriptionIngredients.map(i => `• ${i.name}: ${i.reason}`).join('\n')}

PERSONALIZED ROUTINE:

MORNING:
${analysisResults.routine.filter(s => s.time === 'AM' || s.time === 'BOTH').map(s => `${s.step}. ${s.product}\n   Reason: ${s.reason}`).join('\n')}

EVENING:
${analysisResults.routine.filter(s => s.time === 'PM' || s.time === 'BOTH').map(s => `${s.step}. ${s.product}\n   Reason: ${s.reason}`).join('\n')}

===================================
Generated by Dermatological Intelligence
    `;

    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'skin-analysis-report.txt';
    a.click();
    URL.revokeObjectURL(url);
    toast.success('Report downloaded!');
  };

  return (
    <div className="min-h-screen pb-24">
      {/* Header */}
      <header className="sticky top-0 z-40 glass-card mx-4 mt-4 mb-6 rounded-2xl">
        <div className="flex items-center justify-center gap-2 py-4">
          <Sparkles className="w-5 h-5 text-primary" />
          <h1 className="text-lg font-semibold bg-gradient-to-r from-primary to-secondary bg-clip-text text-transparent">
            Dermatological Intelligence
          </h1>
        </div>
      </header>

      <main className="px-4 space-y-6">
        {activeTab === 'scan' && (
          <>
            {!analysisResults ? (
              <>
                {/* Skin Profile Form */}
                <SkinForm onSubmit={handleFormSubmit} isValid={!!isFormValid} />

                {/* Image Capture */}
                <ImageCapture
                  onImageCapture={handleImageCapture}
                  isScanning={isScanning}
                  showValidationWarning={showValidationWarning}
                  onDismissWarning={() => setShowValidationWarning(false)}
                />

                {/* Initiate Analysis Button */}
                {imageData && !isScanning && (
                  <button
                    onClick={handleStartAnalysis}
                    disabled={isScanning}
                    className="w-full py-4 rounded-2xl bg-gradient-to-r from-primary to-secondary text-primary-foreground font-semibold text-lg pulse-glow btn-shine disabled:opacity-50 disabled:cursor-not-allowed"
                  >
                    Initiate Diagnostic
                  </button>
                )}
              </>
            ) : (
              <>
                {/* Back button */}
                <button
                  onClick={() => {
                    setAnalysisResults(null);
                    setImageData(null);
                  }}
                  className="text-sm text-muted-foreground hover:text-foreground transition-colors"
                >
                  ← New Analysis
                </button>

                {/* Analysis Results */}
                <AnalysisResults data={analysisResults} onDownloadReport={handleDownloadReport} />
              </>
            )}
          </>
        )}

        {activeTab === 'history' && (
          <div className="glass-card p-8 text-center">
            <p className="text-muted-foreground">Analysis history coming soon</p>
          </div>
        )}

        {activeTab === 'settings' && (
          <div className="glass-card p-8 text-center">
            <p className="text-muted-foreground">Settings coming soon</p>
          </div>
        )}
      </main>

      {/* Bottom Navigation */}
      <BottomNav activeTab={activeTab} onTabChange={setActiveTab} />
    </div>
  );
}
